<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 4x4 matrix of random integers between 1 and 100
matrix = np.random.randint(1, 101, (4, 4))
print("4x4 Random Integer Matrix:")
print(matrix)

# Operations
print("\nShape:- ", matrix.shape)
print("Dimension (ndim):- ", matrix.ndim)
print("Total number of elements (size):- ", matrix.size)
print("Data Type:- ", matrix.dtype)
print("Maximum value:- ", matrix.max())
print("Minimum value:- ", matrix.min())


4x4 Random Integer Matrix:
[[ 5 10 15 72]
 [34 81 41 37]
 [ 5 54 90  6]
 [14 52 65 76]]

Shape:-  (4, 4)
Dimension (ndim):-  2
Total number of elements (size):-  16
Data Type:-  int64
Maximum value:-  90
Minimum value:-  5
