<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#  A 1D array of 10 random numbers between 0 and 1 using np.random.rand()
arr1 = np.random.rand(10)
print("\na). 1D array of 10 random numbers between 0 and 1:")
print(" ", arr1)

#  A 3x3 matrix of random numbers from standard normal distribution using np.random.randn()
arr2 = np.random.randn(3, 3)
print("\nb). 3x3 matrix of random numbers from standard normal distribution:")
print(" ", arr2)

# A 2D array 4x5 of random integers between 10 and 50 using np.random.randint()
arr3 = np.random.randint(10, 51, (4, 5))
print("\nc). 2D array of shape 4x5 of random integers between 10 and 50:")
print(" ", arr3)


a). 1D array of 10 random numbers between 0 and 1:
  [0.25517702 0.10099877 0.9454007  0.1792342  0.20374566 0.51503119
 0.6713654  0.65007265 0.42656456 0.8622546 ]

b). 3x3 matrix of random numbers from standard normal distribution:
  [[ 1.08013393  0.36815723 -0.96261989]
 [-0.97727774  1.45719618  0.15403819]
 [ 0.44143299  1.12097401  0.56525642]]

c). 2D array of shape 4x5 of random integers between 10 and 50:
  [[18 18 13 39 36]
 [48 48 25 33 30]
 [10 31 44 48 47]
 [28 29 36 25 35]]
