<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

v1 = np.array([ 2, 4, 6, 8 ])
v2 = np.array([ 1, 3, 5, 7 ])

# Create vectors
print("Array 1:", v1)
print("Array 2:", v2)

# Addition
print("\nAddition:")
a = v1 + v2
print(a)

# Subtraction
print("\nSubtraction:")
s = v1 - v2
print(s)

# Multiplication
print("\nElement-wise Multiplication:")
m = v1 * v2
print(m)

# Dot Product
print("\nDot Product:")
d = np.dot(v1, v2)
print(d)

Array 1: [2 4 6 8]
Array 2: [1 3 5 7]

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100
