<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1D array of 8 zeros
arr1 = np.zeros(8)

# 2D array of shape 4, 4) filled with ones
arr2 = np.ones((4,4))

# 3x3 matrix of zeros
arr3 = np.zeros((3,3))

print("1. 1D Array of 8 zeros:")
print(arr1)

print("\n2. 2D Array of 4 x 4 ones:")
print(arr2)

print("\n3. 2D Array of 3 x 3 zeros:")
print(arr3)

1. 1D Array of 8 zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

2. 2D Array of 4 x 4 ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3. 2D Array of 3 x 3 zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
