<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create two 3 3 matrices:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("1) Matrix A:")
print(" ", A)

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("\n2) Matrix B:")
print(" ",B)

# Operations
print("\nAddition:")
add = A + B
print(add)

print("\nMatrix Multiplication:")
mul = A @ B
print(mul)

print("\nElement-wise Multiplication:")
elem_mul = A * B
print(elem_mul)

1) Matrix A:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]

2) Matrix B:
  [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
