<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# 1D array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array: ")
print(arr1)
print("Shape: ", arr1.shape)
print("Data type: ", arr1.dtype)

# 2D array of 3 x 3
arr2 = np.array([[10,20,30], [40,50,60], [70,80,90]])
print("\n2D Array: ")
print(arr2)
print("Shape: ", arr2.shape)
print("Data type: ", arr2.dtype)


1D Array: 
[10 20 30 40 50]
Shape:  (5,)
Data type:  int64

2D Array: 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape:  (3, 3)
Data type:  int64
