<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#  Simple Statistics Calculator
import numpy as np

try:
  # Ask userfor number of elements
  num = int(input("Enter how many number wants to generate: "))

  if num <= 0:
    raise ValueError("Number must be greater than 0")

  # Generate random numbers between 10 and 100
  arr = np.random.randint(10, 101, num)

  print("\nGenerated Array: ")
  print(arr)

  print("\nOperations:")
  print("Mean: ", np.mean(arr))
  print("Median:", np.median(arr))
  print("Standard Deviation:", np.std(arr))
  print("Minimum:", np.min(arr))
  print("Maximum:", np.max(arr))

  # Try reshaping into 2D matrix
  rows = int(np.sqrt(num))

  if rows > 1 and num % rows == 0:
    colm = num // rows
    matrix = arr.reshape(rows, colm)

    print("\nReshaped 2D Array:")
    print(matrix)

    # Row-wise sum
    print("\nRow-wise Sum:")
    print(np.sum(matrix, axis=1))

  else:
    print("\nReshaping into a proper 2D array is not possible.")

except ValueError as e:
    print("Invalid Input:", e)

except Exception as e:
    print("Error:", e)

finally:
    print("\nProgram executed.")


Enter how many number wants to generate: 12

Generated Array: 
[59 72 59 12 41 46 12 50 39 76 42 11]

Operations:
Mean:  43.25
Median: 44.0
Standard Deviation: 21.342934037599736
Minimum: 11
Maximum: 76

Reshaped 2D Array:
[[59 72 59 12]
 [41 46 12 50]
 [39 76 42 11]]

Row-wise Sum:
[202 149 168]

Program executed.
