<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project/blob/main/Program_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1D array of 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)
print("1D Array: ")
print(arr)

# Reshape the array into a 4x5 matrix
matrix = arr.reshape(4, 5)
print("\nReshaped Matrix: ")
print(matrix)

# Calculate the sum, mean, standard deviation, and maximum value of the matrix
sum = matrix.sum()
print("\nSum: ", sum)

mean = matrix.mean()
print("Mean: ", mean)

std_dev = matrix.std()
print("Standard Deviation: ", std_dev)

row_max = matrix.max()
print("Maximum Value in each row: ", row_max)


1D Array: 
[ 3 23 29 34  7  8 45 13 40 28 49 15 30  5 41  7  6 26 41 17]

Reshaped Matrix: 
[[ 3 23 29 34  7]
 [ 8 45 13 40 28]
 [49 15 30  5 41]
 [ 7  6 26 41 17]]

Sum:  467
Mean:  23.35
Standard Deviation:  14.636512562765764
Maximum Value in each row:  49
